name: Demo Workflow 2
on: push
jobs:
 Demo-Job:
   runs-on: ubuntu-latest
   steps:
     - name: Check out repository code
       uses: actions/checkout@v4

     - name: List files in the repository
       run: |
         echo "Listing files in the repository(${{ github.workspace }}).."
         ls ${{ github.workspace }}
     - run: echo "Job's status is ${{ job.status }}"

     - name: Print the readme file
       run: |
         cat README.md 


